export const sessionKeys = {
  answers: {
    cattle: 'cattle',
    cattleType: 'cattleType',
    pigs: 'pigs',
    sheep: 'sheep'
  },
  farmerApplyData: {
    eligibleSpecies: 'eligibleSpecies',
    declaration: 'declaration',
    organisation: 'organisation',
    whichReview: 'whichReview',
    confirmCheckDetails: 'confirmCheckDetails',
    reference: 'reference',
    urnResult: 'urnResult',
    vetName: 'vetName',
    vetRcvs: 'vetRcvs',
    visitDate: 'visitDate',
    dateOfTesting: 'dateOfTesting'
  },
  endemicsClaim: {
    biosecurity: 'biosecurity',
    diseaseStatus: 'diseaseStatus',
    reference: 'reference',
    typeOfLivestock: 'typeOfLivestock',
    typeOfReview: 'typeOfReview',
    dateOfVisit: 'dateOfVisit',
    dateOfTesting: 'dateOfTesting',
    vetsName: 'vetsName',
    vetRCVSNumber: 'vetRCVSNumber',
    herdVaccinationStatus: 'herdVaccinationStatus',
    laboratoryURN: 'laboratoryURN',
    numberOfOralFluidSamples: 'numberOfOralFluidSamples',
    numberOfSamplesTested: 'numberOfSamplesTested',
    numberAnimalsTested: 'numberAnimalsTested',
    minimumNumberAnimalsRequired: 'minimumNumberAnimalsRequired',
    testResults: 'testResults',
    vetVisitsReviewTestResults: 'vetVisitsReviewTestResults',
    organisation: 'organisation',
    speciesNumbers: 'speciesNumbers',
    sheepEndemicsPackage: 'sheepEndemicsPackage',
    latestEndemicsApplication: 'latestEndemicsApplication',
    latestVetVisitApplication: 'latestVetVisitApplication',
    relevantReviewForEndemics: 'relevantReviewForEndemics',
    sheepTests: 'sheepTests',
    sheepTestResults: 'sheepTestResults',
    previousClaims: 'previousClaims',
    reviewTestResults: 'reviewTestResults',
    piHunt: 'piHunt',
    piHuntAllAnimals: 'piHuntAllAnimals',
    piHuntRecommended: 'piHuntRecommended',
    amount: 'amount',
    tempHerdId: 'tempHerdId',
    herdSelected: 'herdSelected',
    herdId: 'herdId',
    herdVersion: 'herdVersion',
    herdName: 'herdName',
    herdCph: 'herdCph',
    isOnlyHerdOnSbi: 'isOnlyHerdOnSbi',
    herdReasons: 'herdReasons',
    herdSame: 'herdSame',
    herds: 'herds',
    pigsFollowUpTest: 'pigsFollowUpTest',
    pigsElisaTestResult: 'pigsElisaTestResult',
    pigsPcrTestResult: 'pigsPcrTestResult',
    pigsGeneticSequencing: 'pigsGeneticSequencing'
  },
  claim: {
    animalsTested: 'animalsTested',
    detailsCorrect: 'detailsCorrect',
    claimed: 'claimed'
  },
  pkcecodes: {
    verifier: 'verifier'
  },
  tokens: {
    accessToken: 'accessToken',
    tokenExpiry: 'tokenExpiry',
    idToken: 'idToken',
    state: 'state',
    nonce: 'nonce'
  },
  customer: {
    id: 'id',
    crn: 'crn',
    organisationId: 'organisationId',
    attachedToMultipleBusinesses: 'attachedToMultipleBusinesses'
  },
  tempClaimReference: 'tempClaimReference'
}
