version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-ahwr-farmer-claim:
    build:
      target: development
    image: ffc-ahwr-farmer-claim-development
    container_name: ffc-ahwr-farmer-claim-development
    environment:
      USE_PRETTY_PRINT: ${USE_PRETTY_PRINT:-true}
      DEV_LOGIN_ENABLED: ${DEV_LOGIN_ENABLED:-true}
    ports:
      - "3004:3000"
      - "9234:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  redis:
    image: redis:4.0.14
    volumes:
      - redis_data:/data
    ports:
      - "6384:6379"

volumes:
  azurite_data:
  redis_data: