version: "3.8"

services:
  ffc-ahwr-farmer-claim:
    build:
      context: .
      target: production
    image: ffc-ahwr-farmer-claim
    container_name: ffc-ahwr-farmer-claim
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-farmer-claim-local
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      COOKIE_PASSWORD: who-likes-cookies-i-like-cookies-everybody-likes-cookies
      EVENT_QUEUE_ADDRESS: ${EVENT_QUEUE_ADDRESS:-ffc-ahwr-event}${MESSAGE_QUEUE_SUFFIX}
      GOOGLE_TAG_MANAGER_KEY: ${GOOGLE_TAG_MANAGER_KEY}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      SERVICE_URI: http://localhost:3004/claim
      APPLY_SERVICE_URI: http://localhost:3000/apply
      DASHBOARD_SERVICE_URI: http://localhost:3003
      APPLICATION_API_URI: http://host.docker.internal:3001/api
      DEFRA_ID_TENANT: ${DEFRA_ID_TENANT:-azdcuspoc5}
      DEFRA_ID_POLICY: ${DEFRA_ID_POLICY:-B2C_1A_SIGNUPSIGNINSFI}
      DEFRA_ID_REDIRECT_URI: ${DEFRA_ID_REDIRECT_URI:-http://localhost:3000/apply/signin-oidc}
      DEFRA_ID_DASHBOARD_REDIRECT_URI: ${DEFRA_ID_DASHBOARD_REDIRECT_URI:-http://localhost:3003/signin-oidc}
      DEFRA_ID_JWT_ISSUER_ID: ${DEFRA_ID_JWT_ISSUER_ID:-changeme}
      DEFRA_ID_CLIENT_ID: ${DEFRA_ID_CLIENT_ID:-changeme}
      DEFRA_ID_CLIENT_SECRET: ${DEFRA_ID_CLIENT_SECRET:-changeme}
      DEFRA_ID_SERVICE_ID: ${DEFRA_ID_SERVICE_ID:-2a672ee6-7750-ed11-bba3-000d3adf7047}
      RPA_HOST_NAME: ${RPA_HOST_NAME:-https://dev-internal-gateway.trade.azure.defra.cloud}
      RPA_GET_PERSON_SUMMARY_URL: ${RPA_GET_PERSON_SUMMARY_URL:-/rural-payments-vet-visits/v1/person/3337243/summary}
      RPA_GET_ORGANISATION_PERMISSIONS_URL: ${RPA_GET_ORGANISATION_PERMISSIONS_URL:-/rural-payments-vet-visits/v1/SitiAgriApi/authorisation/organisation/organisationId/authorisation}
      RPA_GET_ORGANISATION_URL: ${RPA_GET_ORGANISATION_URL:-/rural-payments-vet-visits/v1/organisation/organisationId}
      APIM_OCP_SUBSCRIPTION_KEY: ${APIM_OCP_SUBSCRIPTION_KEY:-changeme}
      APIM_HOST_NAME: ${APIM_HOST_NAME:-https://login.microsoftonline.com}
      APIM_OAUTH_PATH: ${APIM_OAUTH_PATH:-/c9d74090-b4e6-4b04-981d-e6757a160812/oauth2/v2.0/token}
      APIM_CLIENT_ID: ${APIM_CLIENT_ID:-changeme}
      APIM_CLIENT_SECRET: ${APIM_CLIENT_SECRET:-changeme}
      APIM_SCOPE: ${APIM_SCOPE:-api://dev-futuretrade-int.defra.gov.uk/.default}
      DATE_OF_TESTING_ENABLED: ${DATE_OF_TESTING_ENABLED:-false}
      ENDEMICS_ENABLED: ${ENDEMICS_ENABLED:-true}
      OPTIONAL_PIHUNT_ENABLED: ${OPTIONAL_PIHUNT_ENABLED:-true}
      MULTI_SPECIES_ENABLED: ${MULTI_SPECIES_ENABLED:-true}
      MULTI_HERDS_ENABLED: ${MULTI_HERDS_ENABLED:-true}
      CUSTOMER_SURVEY_CLAIM_URI: ${CUSTOMER_SURVEY_CLAIM_URI:-https://forms.office.com/Pages/ResponsePage.aspx?id=UCQKdycCYkyQx044U38RAsIdAEqqafZCk2LjifrI4h1UOVJKOVRUWlBLMEpFQVdERzA3QVRFWUM2NS4u}