version: '3.8'

services:
  ffc-ahwr-farmer-claim:
    build:
      context: .
      target: production
    image: ffc-ahwr-farmer-claim
    container_name: ffc-ahwr-farmer-claim
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-farmer-claim-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
