version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-ahwr-farmer-claim:
    build:
      target: development
    image: ffc-ahwr-farmer-claim-development
    container_name: ffc-ahwr-farmer-claim-development
    ports:
      - "3004:3000"
      - "9234:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  ffc-ahwr-farmer-claim-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.16.0
    volumes:
      - azurite_data:/data
    ports:
      - "10002:10000"
      - "10003:10001"
    command: "azurite --loose --skipApiVersionCheck --queueHost 0.0.0.0 --blobHost 0.0.0.0 --tableHost 0.0.0.0"

  redis:
    image: redis:4.0.14
    volumes:
      - redis_data:/data
    ports:
      - "6381:6379"

volumes:
  azurite_data:
  redis_data: