version: "3.8"

services:
  ffc-ahwr-farmer-claim:
    command: npm run start:watch
    build:
      target: development
    image: ffc-ahwr-farmer-claim-development
    environment:
      NODE_ENV: test
    volumes:
      - ./test-output/:/home/node/test-output/

  zap-baseline-scan:
    image: owasp/zap2docker-stable:2.14.0
    command: echo 12345
    depends_on:
      - ffc-ahwr-farmer-claim
    volumes:
      - ./test-output/:/zap/wrk/test-output/
      - ./zap/:/zap/wrk/config/
