services:
  ffc-ahwr-farmer-claim:
    build:
      context: .
      target: production
    image: ffc-ahwr-farmer-claim
    container_name: ffc-ahwr-farmer-claim
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-farmer-claim-local
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      COOKIE_PASSWORD: who-likes-cookies-i-like-cookies-everybody-likes-cookies
      EVENT_QUEUE_ADDRESS: ${EVENT_QUEUE_ADDRESS:-ffc-ahwr-event}${MESSAGE_QUEUE_SUFFIX}
      GOOGLE_TAG_MANAGER_KEY: ${GOOGLE_TAG_MANAGER_KEY}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      SERVICE_URI: http://localhost:3004/claim
      APPLY_SERVICE_URI: http://localhost:3000/apply
      DASHBOARD_SERVICE_URI: http://localhost:3003
      APPLICATION_API_URI: http://host.docker.internal:3001/api
      DEFRA_ID_TENANT: ${DEFRA_ID_TENANT:-azdcuspoc5}
      DEFRA_ID_POLICY: ${DEFRA_ID_POLICY:-B2C_1A_SIGNUPSIGNINSFI}
      DEFRA_ID_CLIENT_ID: ${DEFRA_ID_CLIENT_ID:-changeme}
      DEFRA_ID_SERVICE_ID: ${DEFRA_ID_SERVICE_ID:-2a672ee6-7750-ed11-bba3-000d3adf7047}
      PIG_UPDATES_ENABLED: ${PIG_UPDATES_ENABLED:-true}
      CUSTOMER_SURVEY_CLAIM_URI: ${CUSTOMER_SURVEY_CLAIM_URI:-https://forms.office.com/Pages/ResponsePage.aspx?id=UCQKdycCYkyQx044U38RAsIdAEqqafZCk2LjifrI4h1UOVJKOVRUWlBLMEpFQVdERzA3QVRFWUM2NS4u}