{{- include "ffc-helm-library.container-config-map" (list . "ffc-ahwr-farmer-claim.config-map") -}}
{{- define "ffc-ahwr-farmer-claim.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  NAMESPACE: {{ quote .Values.namespace }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  EVENT_QUEUE_ADDRESS: {{ .Values.container.eventQueueAddress }}
  GOOGLE_TAG_MANAGER_KEY: {{ quote .Values.container.googleTagManagerKey }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  {{- if .Values.container.redisHostname }}
  REDIS_HOSTNAME: {{ quote .Values.container.redisHostname }}
  {{- end }}
  {{- if .Values.pr }}
  REDIS_PARTITION: {{ .Values.container.redisPartition }}-{{ .Values.pr }}
  {{ else }}
  REDIS_PARTITION: {{ quote .Values.container.redisPartition }}
  {{- end }}
  REDIS_PORT: {{ quote .Values.container.redisPort }}
  SERVICE_URI: {{ quote .Values.container.serviceUri }}
  APPLY_SERVICE_URI: {{ quote .Values.container.applyServiceUri }}
  DASHBOARD_SERVICE_URI: {{ quote .Values.container.dashboardServiceUri }}
  APPLICATION_API_URI: {{ quote .Values.container.applicationApiUri }}
  DEFRA_ID_TENANT: {{ quote .Values.container.defraIdTenant }}
  DEFRA_ID_POLICY: {{ quote .Values.container.defraIdPolicy }}
  DEFRA_ID_DASHBOARD_REDIRECT_URI: {{ quote .Values.container.defraIdDashboardRedirectUri }}
  DEFRA_ID_JWT_ISSUER_ID: {{ quote .Values.container.defraIdJwtIssuerId }}
  RPA_HOST_NAME: {{ quote .Values.container.rpaHostname }}
  RPA_GET_PERSON_SUMMARY_URL: {{ quote .Values.container.rpaGetPersonSummaryUrl }}
  RPA_GET_ORGANISATION_PERMISSIONS_URL: {{ quote .Values.container.rpaGetOrganisationPermissionsUrl }}
  RPA_GET_ORGANISATION_URL: {{ quote .Values.container.rpaGetOrganisationUrl }}
  APIM_HOST_NAME: {{ quote .Values.container.apimHostname }}
  APIM_OAUTH_PATH: {{ quote .Values.container.apimOAuthPath }}
  APIM_SCOPE: {{ quote .Values.container.apimScope }}
  WRECK_HTTP_TIMEOUT_MILLISECONDS: {{ quote .Values.wreckHttp.timeoutMilliseconds }}
  DATE_OF_TESTING_ENABLED: {{ quote .Values.container.dateOfTestingEnabled }}
  MULTI_SPECIES_ENABLED: {{ quote .Values.container.multiSpeciesEnabled }}
  MULTI_HERDS_ENABLED: {{ quote .Values.container.multiHerdsEnabled }}
  MULTI_HERDS_RELEASE_DATE: {{ quote .Values.container.multiHerdsReleaseDate }}
  DEV_LOGIN_ENABLED: {{ quote .Values.container.devLoginEnabled }}
  CUSTOMER_SURVEY_CLAIM_URI: {{ quote .Values.container.customerSurveyClaimUri }}
{{- end -}}
