const config = require('../config')

module.exports = {
  vetVisits: config.vetVisits,
  endemicsIndex: 'endemics',
  endemicsBiosecurity: 'endemics/biosecurity',
  endemicsCheckAnswers: 'endemics/check-answers',
  endemicsConfirmation: 'endemics/confirmation',
  endemicsDateOfTesting: 'endemics/date-of-testing',
  endemicsDateOfVisit: 'endemics/date-of-visit',
  endemicsDateOfVisitException: 'endemics/date-of-visit-exception',
  endemicsDiseaseStatus: 'endemics/disease-status',
  endemicsEndemicsPackage: 'endemics/endemics-package',
  endemicsNumberOfOralFluidSamples: 'endemics/number-of-fluid-oral-samples',
  endemicsNumberOfOralFluidSamplesException: 'endemics/number-of-fluid-oral-samples-exception',
  endemicsNumberOfSpeciesTested: 'endemics/number-of-species-tested',
  endemicsNumberOfSpeciesException: 'endemics/number-of-species-exception',
  endemicsNumberOfSpeciesSheepException: 'endemics/number-of-species-sheep-exception',
  endemicsNumberOfTests: 'endemics/number-of-tests',
  endemicsSpeciesNumbers: 'endemics/species-numbers',
  endemicsSpeciesNumbersException: 'endemics/species-numbers-exception',
  endemicsTestResults: 'endemics/test-results',
  endemicsTestUrn: 'endemics/test-urn',
  endemicsWhichSpecies: 'endemics/which-species',
  endemicsWhichTypeOfReview: 'endemics/which-type-of-review',
  endemicsVaccination: 'endemics/vaccination',
  endemicsVetName: 'endemics/vet-name',
  endemicsVetRCVS: 'endemics/vet-rcvs',
  endemicsYouCannotClaim: 'endemics/you-cannot-claim'
}
