environment: development
name: ffc-ahwr-farmer-claim
namespace: ffc-ahwr
workstream: ffc-ahwr
image: ffc-ahwr-farmer-claim

labels: {}

aadPodIdentity: true

appInsights:
  connectionString:

azureIdentity:
  clientID:
  resourceID:

containerConfigMap:
  name: ffc-ahwr-farmer-claim-config-map

containerSecret:
  name: ffc-ahwr-farmer-claim-container-secret
  type: Opaque

deployment:
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 2
  priorityClassName: default
  replicas: 1
  restartPolicy: Always

container:
  applicationRequestQueueAddress: ffc-ahwr-application-request
  applicationResponseQueueAddress: ffc-ahwr-application-response
  cookiePassword: who-likes-cookies-i-like-cookies-everybody-likes-cookies
  eventQueueAddress: ffc-ahwr-event
  googleTagManagerKey:
  imagePullPolicy: IfNotPresent
  requestMemory: 100Mi
  requestCpu: 40m
  limitMemory: 100Mi
  limitCpu: 100m
  messageQueueHost: namespace.servicebus.windows.net
  notifyApiKey:
  notifyTemplateIdFarmerClaimLogin:
  port: 3000
  redisHostname: redis-hostname.default
  redisPartition: ffc-ahwr-farmer-claim
  redisPassword: redis
  redisPort: 6379
  serviceUri:
  applyServiceUri:
  eligibilityApiUri:
  applicationApiUri:
  defraIdEnabled:
  defraIdTenant:
  defraIdRedirectUri:
  defraIdClientId:
  defraIdClientSecret:
  defraIdServiceId:
  defraIdPolicy:
  
ingress:
  class: nginx
  endpoint: ffc-ahwr-farmer
  server: value.replaced.from.app.config
  path: /claim
  type: minion

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

service:
  port: 80
  type: ClusterIP